In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
data = pd.read_csv("Airline_Delay_cause.csv")

In [6]:
print(data.head())
print(data.describe())

   year  month carrier       carrier_name airport  \
0  2022      5      9E  Endeavor Air Inc.     ABE   
1  2022      5      9E  Endeavor Air Inc.     ABY   
2  2022      5      9E  Endeavor Air Inc.     ACK   
3  2022      5      9E  Endeavor Air Inc.     AEX   
4  2022      5      9E  Endeavor Air Inc.     AGS   

                                        airport_name  arr_flights  arr_del15  \
0  Allentown/Bethlehem/Easton, PA: Lehigh Valley ...        136.0        7.0   
1             Albany, GA: Southwest Georgia Regional         91.0       16.0   
2                  Nantucket, MA: Nantucket Memorial         19.0        2.0   
3           Alexandria, LA: Alexandria International         88.0       14.0   
4        Augusta, GA: Augusta Regional at Bush Field        181.0       19.0   

   carrier_ct  weather_ct  ...  security_ct  late_aircraft_ct  arr_cancelled  \
0        5.95        0.00  ...          0.0              1.00            0.0   
1        7.38        0.00  ...          

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318017 entries, 0 to 318016
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   year                 318017 non-null  int64  
 1   month                318017 non-null  int64  
 2   carrier              318017 non-null  object 
 3   carrier_name         318017 non-null  object 
 4   airport              318017 non-null  object 
 5   airport_name         318017 non-null  object 
 6   arr_flights          317529 non-null  float64
 7   arr_del15            317289 non-null  float64
 8   carrier_ct           317529 non-null  float64
 9   weather_ct           317529 non-null  float64
 10  nas_ct               317529 non-null  float64
 11  security_ct          317529 non-null  float64
 12  late_aircraft_ct     317529 non-null  float64
 13  arr_cancelled        317529 non-null  float64
 14  arr_diverted         317529 non-null  float64
 15  arr_delay        

In [9]:
data.shape

(318017, 21)

In [10]:
data.duplicated().sum()

0

In [11]:
data['airport_name'].unique()

array(['Allentown/Bethlehem/Easton, PA: Lehigh Valley International',
       'Albany, GA: Southwest Georgia Regional',
       'Nantucket, MA: Nantucket Memorial',
       'Alexandria, LA: Alexandria International',
       'Augusta, GA: Augusta Regional at Bush Field',
       'Albany, NY: Albany International',
       'Atlanta, GA: Hartsfield-Jackson Atlanta International',
       'Appleton, WI: Appleton International',
       'Austin, TX: Austin - Bergstrom International',
       'Asheville, NC: Asheville Regional',
       'Kalamazoo, MI: Kalamazoo/Battle Creek International',
       'Binghamton, NY: Greater Binghamton/Edwin A. Link Field',
       'Bangor, ME: Bangor International',
       'Birmingham, AL: Birmingham-Shuttlesworth International',
       'Bloomington/Normal, IL: Central Il Regional Airport at Bloomington',
       'Nashville, TN: Nashville International',
       'Boston, MA: Logan International',
       'Brunswick, GA: Brunswick Golden Isles',
       'Baton Rouge, LA: Bat

In [12]:
data.corr()

year     month  arr_flights  arr_del15  carrier_ct  \
year                 1.000000 -0.072363    -0.025699  -0.052957   -0.035570   
month               -0.072363  1.000000     0.003852  -0.000387    0.002263   
arr_flights         -0.025699  0.003852     1.000000   0.918808    0.883630   
arr_del15           -0.052957 -0.000387     0.918808   1.000000    0.908627   
carrier_ct          -0.035570  0.002263     0.883630   0.908627    1.000000   
weather_ct          -0.061241 -0.012914     0.613742   0.666306    0.692905   
nas_ct              -0.066217 -0.001083     0.807462   0.920773    0.734855   
security_ct         -0.042988  0.009947     0.473536   0.484547    0.506949   
late_aircraft_ct    -0.034567  0.000819     0.868245   0.931671    0.838892   
arr_cancelled        0.009889 -0.049273     0.499151   0.517991    0.463856   
arr_diverted        -0.008427 -0.004105     0.637867   0.668901    0.594386   
arr_delay           -0.022239 -0.003540     0.880518   0.974156    0.875712   
carrier_delay        0.011171 -0.002803     0.872491   0.884304    0.944229   
weather_delay       -0.024313 -0.016250     0.621287   0.675524    0.684723   
nas_delay           -0.050084 -0.002265     0.699357   0.846295    0.639109   
security_delay      -0.017084  0.008644     0.417122   0.420711    0.440115   
late_aircraft_delay -0.012967 -0.002090     0.845076   0.926802    0.827094   

                     weather_ct    nas_ct  security_ct  late_aircraft_ct  \
year                  -0.061241 -0.066217    -0.042988         -0.034567   
month                 -0.012914 -0.001083     0.009947          0.000819   
arr_flights            0.613742  0.807462     0.473536          0.868245   
arr_del15              0.666306  0.920773     0.484547          0.931671   
carrier_ct             0.692905  0.734855     0.506949          0.838892   
weather_ct             1.000000  0.578238     0.334026          0.531576   
nas_ct                 0.578238  1.000000     0.381294          0.755676   
security_ct            0.334026  0.381294     1.000000          0.472563   
late_aircraft_ct       0.531576  0.755676     0.472563          1.000000   
arr_cancelled          0.399282  0.479334     0.220952          0.477192   
arr_diverted           0.509728  0.609780     0.309649          0.630309   
arr_delay              0.668345  0.905406     0.433051          0.901946   
carrier_delay          0.689061  0.740747     0.430197          0.804668   
weather_delay          0.937151  0.584283     0.322376          0.562724   
nas_delay              0.529991  0.951159     0.315117          0.681906   
security_delay         0.289997  0.342163     0.838118          0.398131   
late_aircraft_delay    0.541872  0.772389     0.434051          0.974779   

                     arr_cancelled  arr_diverted  arr_delay  carrier_delay  \
year                      0.009889     -0.008427  -0.022239       0.011171   
month                    -0.049273     -0.004105  -0.003540      -0.002803   
arr_flights               0.499151      0.637867   0.880518       0.872491   
arr_del15                 0.517991      0.668901   0.974156       0.884304   
carrier_ct                0.463856      0.594386   0.875712       0.944229   
weather_ct                0.399282      0.509728   0.668345       0.689061   
nas_ct                    0.479334      0.609780   0.905406       0.740747   
security_ct               0.220952      0.309649   0.433051       0.430197   
late_aircraft_ct          0.477192      0.630309   0.901946       0.804668   
arr_cancelled             1.000000      0.382440   0.536771       0.485570   
arr_diverted              0.382440      1.000000   0.694098       0.623635   
arr_delay                 0.536771      0.694098   1.000000       0.905581   
carrier_delay             0.485570      0.623635   0.905581       1.000000   
weather_delay             0.426073      0.555868   0.710155       0.718773   
nas_delay                 0.476676      0.593597   0.882103    

In [14]:
data[data['weather_delay'] > 1000][['airport_name', 'carrier_name', 'month']].head(25)

airport_name  \
6    Atlanta, GA: Hartsfield-Jackson Atlanta Intern...   
56         New York, NY: John F. Kennedy International   
60                             New York, NY: LaGuardia   
80    Raleigh/Durham, NC: Raleigh-Durham International   
103       Austin, TX: Austin - Bergstrom International   
109                    Boston, MA: Logan International   
116     Charlotte, NC: Charlotte Douglas International   
120  Washington, DC: Ronald Reagan Washington National   
122  Dallas/Fort Worth, TX: Dallas/Fort Worth Inter...   
142        New York, NY: John F. Kennedy International   
145         Los Angeles, CA: Los Angeles International   
147                            New York, NY: LaGuardia   
151                 Orlando, FL: Orlando International   
155                     Miami, FL: Miami International   
166          Chicago, IL: Chicago O'Hare International   
170       Philadelphia, PA: Philadelphia International   
171      Phoenix, AZ: Phoenix Sky Harbor International   
177   Raleigh/Durham, NC: Raleigh-Durham International   
273          Seattle, WA: Seattle/Tacoma International   
292                    Boston, MA: Logan International   
304           Newark, NJ: Newark Liberty International   
306  Fort Lauderdale, FL: Fort Lauderdale-Hollywood...   
311        New York, NY: John F. Kennedy International   
314                            New York, NY: LaGuardia   
355  Atlanta, GA: Hartsfield-Jackson Atlanta Intern...   

               carrier_name  month  
6         Endeavor Air Inc.      5  
56        Endeavor Air Inc.      5  
60        Endeavor Air Inc.      5  
80        Endeavor Air Inc.      5  
103  American Airlines Inc.      5  
109  American Airlines Inc.      5  
116  American Airlines Inc.      5  
120  American Airlines Inc.      5  
122  American Airlines Inc.      5  
142  American Airlines Inc.      5  
145  American Airlines Inc.      5  
147  American Airlines Inc.      5  
151  American Airlines Inc.      5  
155  American Airlines Inc.      5  
166  American Airlines Inc.      5  
170  American Airlines Inc.      5  
171  American Airlines Inc.      5  
177  American Airlines Inc.      5  
273    Alaska Airlines Inc.      5  
292         JetBlue Airways      5  
304         JetBlue Airways      5  
306         JetBlue Airways      5  
311         JetBlue Airways      5  
314         JetBlue Airways      5  
355    Delta Air Lines Inc.      5

In [16]:
a = np.array([[1, -2, 4], [2, 0, -1]])
b = np.array([[5, 2, 3], [4, 6, 2]])
a + b

array([[6, 0, 7],
       [6, 6, 1]])

In [17]:
a - b

array([[-4, -4,  1],
       [-2, -6, -3]])

In [27]:
a2 = np.array([[1, 2],[2, -1],[3, 0]])
b2 = np.array([[-1, 1],[1, 2],[0, 0]])
c2 = a2 -3*b2
c2

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

In [28]:
a3 = np.array([[1, -1],[2, 0],[3, 0]])
b3 = np.array([[1, 1],[2, 0]])
c3 = a3 @ b3
c3

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

In [29]:
a4 = np.array([[6, -1, 4],[2, 1, 10],[8, 0, 2]])

np.linalg.det(a4)

-95.99999999999999

In [30]:
a5 = np.array([[3, 3, -1],[4, 1, 3],[1, -2, -2]])
b5 = np.linalg.inv(a5)
b5

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [38]:
c6 = a5 @ b5
detc6 = np.linalg.det(c6)
c7 = b5 @ a5
detc7 =  np.linalg.det(c7)
detc6, detc7

(0.9999999999999998, 1.0)